name: Full Deploy: Frontend + Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-deploy:
    name: Deploy Static Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                ${{ secrets.GITHUB_TOKEN }}
          action:                    upload
          app_location:              "/"        # or "frontend" if your files live there
          skip_app_build:            true       # No npm build step

  backend-deploy:
    name: Deploy Flask Backend
    runs-on: ubuntu-latest
    needs: frontend-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name:           ${{ secrets.AZURE_WEBAPP_NAME }}           # e.g. "my-flask-app"
          slot-name:          production
          publish-profile:    ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package:            backend


